/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Usuario;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import static view.TelaLogin.lista;
import static view.TelaLogin.serial;

/**
 *
 * @author nicolas_nichnig
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    static String[] serial;
    static ArrayList<Usuario> lista;
    Usuario a;
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastro = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        Fotinh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(720, 512));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastro.setText("Cadastro");
        btnCadastro.setBorder(null);
        btnCadastro.setBorderPainted(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 120, 20));

        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 80, 20));

        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 80, 20));

        txtSexo.setBorder(null);
        jPanel1.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 80, 20));

        txtIdade.setBorder(null);
        jPanel1.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 80, 20));

        txtSenha.setBorder(null);
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 80, 20));

        Fotinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela Cadastro.png"))); // NOI18N
        jPanel1.add(Fotinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, 709, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        Cadastro();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        Cadastro();
    }//GEN-LAST:event_btnCadastroActionPerformed
    public void Cadastro(){
    
    String Nome = txtNome.getText();
    String Email = txtEmail.getText();
    int Idade = Integer.parseInt(txtIdade.getText());
    String Sexo = txtSexo.getText();
    String Imagem = null;
    String Senha = txtSenha.getText();
    Boolean Permissao = false;
    Usuario p = new Usuario(Nome, Email, Idade, Sexo, Imagem, Senha, Permissao);
    lista.add(p);
    criarSerial(p);
    String Serial[] = serial;
}
    
        public void criarSerial(Usuario a){
        String[] letras = {"A","B","C","D","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","0","1","2","3","4","5","6","7","8","9"};
        serial = new String[12];
        Random ran = new Random();

            if(a.Permissao){
            serial[0] = letras[ran.nextInt(17)];            
            }
            else{serial[0] = letras[ran.nextInt(17)+17];}

            for(int i = 1; i < 12; i++){
                serial[i] = letras[ran.nextInt(34)];
            }
            a.setSerial(serial);       
    }
    public static void abrir() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fotinh;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
