/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
import classes.Usuario;

/**
 *
 * @author nicolas_nichnig
 */
public class TelaAdmin extends javax.swing.JFrame {
    
    static ArrayList<Usuario> lista;
    String[] serial;
    static Usuario u;
    public TelaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCriar = new javax.swing.JLabel();
        labelEditar = new javax.swing.JLabel();
        labelExcluir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(720, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCriarMouseClicked(evt);
            }
        });
        jPanel1.add(labelCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 180, 140));

        labelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEditarMouseClicked(evt);
            }
        });
        jPanel1.add(labelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 190, 140));

        labelExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExcluirMouseClicked(evt);
            }
        });
        jPanel1.add(labelExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 190, 140));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 180, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela Admin.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCriarMouseClicked
        String Nome = JOptionPane.showInputDialog(this, "Insira o seu nome: ");
        String Email = JOptionPane.showInputDialog(this, "Insira o seu Email: ");
        int Idade = Integer.parseInt(JOptionPane.showInputDialog(this, "Insira a sua idade: "));
        String Sexo = JOptionPane.showInputDialog(this,"Qual é seu sexo?");
        String Imagem = null;
        String Senha = JOptionPane.showInputDialog(this, "Insira sua senha");
        Boolean Permissao = true;
        Usuario p = new Usuario(Nome, Email, Idade, Sexo, Imagem, Senha, Permissao);
        criarSerial(p);
        String[] Serial = serial;
        lista.add(p);
    }//GEN-LAST:event_labelCriarMouseClicked

    private void labelEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEditarMouseClicked
        try{
        String z = JOptionPane.showInputDialog("Insira o email do usuario que queira editar");
        for(Usuario u : lista){            
            if(z.equals(u.getEmail())){
                String btn[] = {"Nome","Email","Idade","Senha","Sexo","Cancelar"};
                int i = JOptionPane.showOptionDialog(this, "Qual deles você quer editar?", "Editar", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, btn, "Cancelar");
                if(i <5){
                    String r = JOptionPane.showInputDialog("Insira o novo termo");
                    switch (i){
                        case 0:
                        u.setNome(r);
                        break;
                        case 1:
                        u.setEmail(r);
                        break;
                        case 2:
                        int b = Integer.parseInt(r);
                        u.setIdade(b);
                        break;
                        case 3:
                        u.setSenha(r);
                        break;
                        case 4:
                        u.setSexo(r);
                        break;
                        default:
                        this.dispose();
                        }
                    }
                }
            }
        }
        catch(Exception e){ JOptionPane.showMessageDialog(this, "Informações não inseridas.");}
    }//GEN-LAST:event_labelEditarMouseClicked

    private void labelExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExcluirMouseClicked
        String z = JOptionPane.showInputDialog("Insira o Serial do usuario que deseja apagar");
        String[] serialArray = z.split("");
        for(Usuario u : lista){
            if(Arrays.equals(serialArray, u.Serial)){
                lista.remove(u);
            }
        }
    }//GEN-LAST:event_labelExcluirMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
                Display.abrir();
    }//GEN-LAST:event_jLabel1MouseClicked

    public void criarSerial(Usuario u){
        String[] letras = {"A","B","C","D","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","0","1","2","3","4","5","6","7","8","9","10"};
        serial = new String[12];
        Random ran = new Random();

            if(u.Permissao){
            serial[0] = letras[ran.nextInt(1)];            
            }
            else{serial[0] = letras[ran.nextInt(34)+1];}

            for(int i = 1; i < 12; i++){
                serial[i] = letras[ran.nextInt(35)];
            }
            u.setSerial(serial);
            
    }
    
    public static void abrir() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCriar;
    private javax.swing.JLabel labelEditar;
    private javax.swing.JLabel labelExcluir;
    // End of variables declaration//GEN-END:variables
    }
