/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import classes.Usuario;

/**
 *
 * @author nicolas_nichnig
 */
public class TelaOpcoes extends javax.swing.JFrame {

    static ArrayList<Usuario> lista;
    static Usuario a;
    public TelaOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEdtNome = new javax.swing.JLabel();
        labelEdtEmail = new javax.swing.JLabel();
        labelEdtSenha = new javax.swing.JLabel();
        labelEdtSex = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEdtNome.setText("Editar Nome");
        labelEdtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEdtNomeMouseClicked(evt);
            }
        });
        getContentPane().add(labelEdtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 204, 130, 20));

        labelEdtEmail.setText("Editar Email");
        labelEdtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEdtEmailMouseClicked(evt);
            }
        });
        getContentPane().add(labelEdtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, -1));

        labelEdtSenha.setText("Editar Senha");
        labelEdtSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEdtSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(labelEdtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 20));

        labelEdtSex.setText("Editar Sexo");
        labelEdtSex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEdtSexMouseClicked(evt);
            }
        });
        getContentPane().add(labelEdtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        btnVoltar.setBackground(new java.awt.Color(0, 180, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela User 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 833, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelEdtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEdtNomeMouseClicked
    int pos = posicao();
    String b = JOptionPane.showInputDialog("Insira seu novo nome");
    a.setNome(b);
    lista.set(pos,a);
    }//GEN-LAST:event_labelEdtNomeMouseClicked

    private void labelEdtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEdtEmailMouseClicked
    int pos = posicao();
    String b = JOptionPane.showInputDialog("Insira seu novo Email");
    a.setEmail(b);
    lista.set(pos, a);
    }//GEN-LAST:event_labelEdtEmailMouseClicked

    private void labelEdtSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEdtSenhaMouseClicked
    int pos = posicao();
    String b = JOptionPane.showInputDialog("Insira sua senha atual");
        if (b.equals(a.getSenha())){
            String f = JOptionPane.showInputDialog("Insira sua nova senha");
            a.setSenha(f);
            lista.set(pos, a);
        }
    }//GEN-LAST:event_labelEdtSenhaMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaUsuario.lista = lista;
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void labelEdtSexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEdtSexMouseClicked
        int pos = posicao();
        String b = JOptionPane.showInputDialog("Insira o sexo desejado");
        a.setSexo(b);
        lista.set(pos, a);
        
    }//GEN-LAST:event_labelEdtSexMouseClicked

    public int posicao(){
        return lista.indexOf(a);
    }
    
    public static void abrir() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelEdtEmail;
    private javax.swing.JLabel labelEdtNome;
    private javax.swing.JLabel labelEdtSenha;
    private javax.swing.JLabel labelEdtSex;
    // End of variables declaration//GEN-END:variables
}
