/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhoacademia;

import java.security.Permission;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolas_nichnig
 */
public class TelaLogin extends javax.swing.JFrame {

    TelaAdmin ta = new TelaAdmin();
    ArrayList<Usuarios> lista = new ArrayList<>();
    String[] serial;
    Usuarios a;
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoEmail = new javax.swing.JTextField();
        campoSenha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoEmail.setText("Email");
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });

        campoSenha.setText("Senha");
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnCadastro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoEmail)
                        .addComponent(campoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addComponent(btnCadastro)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
    try{
    cadastro();
    }
    catch(Exception e){
    jLabel1.setText("Informações erradas");}
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = campoEmail.getText();
        String senha = campoSenha.getText();
        TelaAdmin.lista = lista;
        for(Usuarios a:lista){
        if(a.Email.equals(email) && a.Senha.equals(senha)){
            if(a.Permissao){
                new TelaAdmin().setVisible(true);
                dispose();
            }
            else{JOptionPane.showMessageDialog(this, "User");
            dispose();}
        }
        campoEmail.setText("");
        campoSenha.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cadastro(){
    String Nome = JOptionPane.showInputDialog(this,"Insira seu nome");
    String Email = JOptionPane.showInputDialog(this, "Insira seu Email");
    int Idade = Integer.parseInt(JOptionPane.showInputDialog(this, "insira sua idade"));
    String Sexo = JOptionPane.showInputDialog(this, "Insira seu sexo");
    String Imagem = null;
    String Senha = JOptionPane.showInputDialog(this, "Insira sua senha");
    Boolean Permissao = false;
    Usuarios p = new Usuarios(Nome, Email, Idade, Sexo, Imagem, Senha, Permissao);
    lista.add(p);
    criarSerial(p);
    String Serial[] = serial;
    }
    
    public void cadastroAdmin1(){
    String Nome = "Admin";
    String Email = "Admin";
    int Idade = 35;
    String Serial[] = {"A","D","B","4","2","N","M","2","N","M","7","8"};
    String Sexo = "Masculino";
    String Imagem = null;
    String Senha = "Admin";
    Boolean Permissao = true;
    Usuarios first = new Usuarios(Nome, Email, Idade, Sexo, Imagem, Senha, Permissao);
    lista.add(first);
    }
    
    public void criarSerial(Usuarios a){
        String[] letras = {"A","B","C","D","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","0","1","2","3","4","5","6","7","8","9","10"};
        serial = new String[12];
        Random ran = new Random();

            if(a.Permissao){
            serial[0] = letras[ran.nextInt(17)];            
            }
            else{serial[0] = letras[ran.nextInt(17)+18];}

            for(int i = 1; i < 12; i++){
                serial[i] = letras[ran.nextInt(35)];
            }
            a.setSerial(serial);       
    }
    
    public static void main(String args[]) {
            
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaLogin tl = new TelaLogin();
                tl.setVisible(true);
                tl.cadastroAdmin1();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
